// <auto-generated />
using System;
using CadernosDeErros.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CadernosDeErros.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260722231649_AddUsuarioIdToEntities")]
    partial class AddUsuarioIdToEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CadernosDeErros.Entities.Assunto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MateriaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Assuntos");
                });

            modelBuilder.Entity("CadernosDeErros.Entities.Erro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssuntoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataErro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataRevisao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Explicacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MinhaResposta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Questao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RespostaCorreta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Revisado")
                        .HasColumnType("bit");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssuntoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Erros");
                });

            modelBuilder.Entity("CadernosDeErros.Entities.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("CadernosDeErros.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CadernosDeErros.Entities.Assunto", b =>
                {
                    b.HasOne("CadernosDeErros.Entities.Materia", "Materia")
                        .WithMany("Assuntos")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CadernosDeErros.Entities.Usuario", "Usuario")
                        .WithMany("Assuntos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Materia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CadernosDeErros.Entities.Erro", b =>
                {
                    b.HasOne("CadernosDeErros.Entities.Assunto", "Assunto")
                        .WithMany("Erros")
                        .HasForeignKey("AssuntoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CadernosDeErros.Entities.Usuario", "Usuario")
                        .WithMany("Erros")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assunto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CadernosDeErros.Entities.Materia", b =>
                {
                    b.HasOne("CadernosDeErros.Entities.Usuario", "Usuario")
                        .WithMany("Materias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CadernosDeErros.Entities.Assunto", b =>
                {
                    b.Navigation("Erros");
                });

            modelBuilder.Entity("CadernosDeErros.Entities.Materia", b =>
                {
                    b.Navigation("Assuntos");
                });

            modelBuilder.Entity("CadernosDeErros.Entities.Usuario", b =>
                {
                    b.Navigation("Assuntos");

                    b.Navigation("Erros");

                    b.Navigation("Materias");
                });
#pragma warning restore 612, 618
        }
    }
}
