// <auto-generated />
using System;
using CadernosDeErros.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CadernosDeErros.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CadernosDeErros.Entities.Assunto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MateriaId");

                    b.ToTable("Assuntos");
                });

            modelBuilder.Entity("CadernosDeErros.Entities.Erro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssuntoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataErro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataRevisao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Explicacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MinhaResposta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Questao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RespostaCorreta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Revisado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AssuntoId");

                    b.ToTable("Erros");
                });

            modelBuilder.Entity("CadernosDeErros.Entities.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("CadernosDeErros.Entities.Assunto", b =>
                {
                    b.HasOne("CadernosDeErros.Entities.Materia", "Materia")
                        .WithMany("Assuntos")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("CadernosDeErros.Entities.Erro", b =>
                {
                    b.HasOne("CadernosDeErros.Entities.Assunto", "Assunto")
                        .WithMany("Erros")
                        .HasForeignKey("AssuntoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assunto");
                });

            modelBuilder.Entity("CadernosDeErros.Entities.Assunto", b =>
                {
                    b.Navigation("Erros");
                });

            modelBuilder.Entity("CadernosDeErros.Entities.Materia", b =>
                {
                    b.Navigation("Assuntos");
                });
#pragma warning restore 612, 618
        }
    }
}
